config/routes.rb
Rails.application.routes.draw do
  get 'daily_tasks/create'
  root 'pages#index'
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users do
  end
  resources :users do 
    member do
      get :joinings
      resources :tasks, only: [:new, :create]
      resources :projects, only: [:index, :new, :create] 
    end
  end
  resources :tasks, only: [:show, :update, :edit, :destroy]
  resources :projects, only: [:show, :update, :edit, :destroy] do
    member do
      get :users
    end    
  end
  resources :user_projects, only: [:create, :destroy]
  resources :daily_tasks, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/:id/todo' => 'users#todo'
  get 'users/:id/doing' => 'users#doing'
  get 'users/:id/done' => 'users#done'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validate :password_complexity

  
  validates :name, presence: true, length: { maximum: 50 }
  validates :slackid, presence: true
  
  has_many :user_projects
  has_many :joinings, through: :user_projects, source: :project
  
  has_many :daily_tasks, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :daily_users, dependent: :destroy
  
def password_complexity
  # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
  return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

  errors.add :password, '大文字、小文字、数字、記号を含む8文字以上でパスワードを構成してください'
end

def join(project)
  self.user_projects.find_or_create_by(project_id: project.id)
end

def unjoin(project)
  project = self.user_projects.find_by(project_id: project.id)
  project.destroy if project
end

def joining?(project)
  self.joinings.include?(project)
end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def joinings
    @user = User.find_by(id: params[:id])
    @projects = @user.joinings
  end

  def todo
    @user = User.find_by(id: params[:id])
    @tasks = @user.tasks.where(status: 0).order('created_at DESC')
  end  

  def doing
    # binding.pry
    @tasks_and_daily_tasks = TaskCollection.new(User.find(params[:id]),[],[])
    # binding.pry
    # @daily_tasks = current_user.daily_tasks.where(add_date: Date.today)

    # @daily_tasks = current_user.daily_tasks.where(add_date: Date.today)
    # @tasks = @daily_tasks.map do |daily_task|
    #   daily_task = daily_task.task
    # end
    # @tasks_and_daily_tasks = TaskCollection.new(@daily_tasks,@tasks)
    # binding.pry
  end

  def done
    @user = User.find_by(id: params[:id])
    @tasks = @user.tasks.where(status: 1).order('created_at DESC')
  end

  def show
    @user = User.find_by(id: params[:id])
    @daily_tasks_0 = @user.daily_tasks.where(add_date: Date.today)
    @daily_tasks_1 = @user.daily_tasks.where(add_date: Date.today-1)
    @daily_tasks_2 = @user.daily_tasks.where(add_date: Date.today-2)
    @daily_tasks_3 = @user.daily_tasks.where(add_date: Date.today-3)
    @daily_tasks_4 = @user.daily_tasks.where(add_date: Date.today-4)
    @daily_tasks_5 = @user.daily_tasks.where(add_date: Date.today-5)
    @daily_tasks_6 = @user.daily_tasks.where(add_date: Date.today-6)

    
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/doing.html.erb
<div class="container">
  <div class="mt-3">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><%= link_to "ToDo", "/users/#{current_user.id}/todo", class: 'nav-link btn-secondary', data: {"turbolinks"=>false}%></li>
      <li class="nav-item"><%= link_to "Doing", "/users/#{current_user.id}/doing", class: 'nav-link active', data: {"turbolinks"=>false}%></li>
      <li class="nav-item"><%= link_to "Done", "/users/#{current_user.id}/done", class: 'nav-link btn-secondary', data: {"turbolinks"=>false}%></li>
    </ul>
  </div>


  <%= form_with model: @tasks_and_daily_tasks, url: tasks_path, local: true do |form| %>
    <% if @tasks_and_daily_tasks.errors.any? %>
      <div id="error_explanation alert alert-warning">
        <ul>
          <% @tasks_and_daily_tasks.errors.full_messages.each do |tdt| %>
            <li><%= tdt %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% index = -1 %>
    <% a = false %>
    <% @tasks_and_daily_tasks.collection.each do |daily_task, task|%>
      <% unless daily_task.condition%>
      <% a = true %>
        <div class='task'>
          <% if daily_task.task.project.present? %>
            <span><%= daily_task.task.project.name %>：<%= daily_task.task.content %></span>
          <% end %>
          <% index += 1%>
          <%= fields_for 'tasks[]', task do |field| %>
      
            <div class="field">
              <%= field.hidden_field :task_id, :value => task.id %>
              <%= field.label :status, "Done" %>
              <%= field.check_box(:status, {}, checked_value = 1, unchecked_value = 0 ) %>
            </div>
            </br>
          <% end %>

          <%= fields_for 'daily_tasks[]', daily_task do |field| %>
      
          <div class="field">
            <%= field.hidden_field :daily_task_id, :value => daily_task.id %>
              <i class="fa fa-sun-o form-label" aria-hidden="true"></i>
              <%= field.radio_button :condition, 3, class: 'doing', onclick: 'change();' %>
              <i class="fa fa-cloud form-label" aria-hidden="true"></i>
              <%= field.radio_button :condition, 2, class: 'doing', onclick: 'change();', checked: 'checked' %>
              <i class="fa fa-umbrella form-label" aria-hidden="true"></i>
              <%= field.radio_button :condition, 1, class: 'doing', onclick: 'change();' %>
              <div id="face_<%=index%>"> 
                <%= field.label :comment, "face and think", placeholder:'なぜうまくいかなかったのか、どうしたらうまくいくか' %><br>
                <%= field.text_area :comment %>
              </div>
            <% end %>  
          </div>
          </br>
        </div>
      <% end %>
    <% end %>
    <% if a %>        
      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  <% end %>
</div>

<%= javascript_pack_tag 'users/doing' %>




<% if false %>
  <% @daily_tasks.each do |daily_task| %>
    <% unless daily_task.condition %>
      <span><%= daily_task.task.content %></span>
      <% if current_user %>
        <%= form_with(model: daily_task.task) do |f| %>
          <% if daily_task.task.errors.any? %>
            <div id="error_explanation">
              <ul>
                <% daily_task.task.errors.full_messages.each do |dt| %>
                  <li><%= dt %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class='border-bottom p-1 mb-2'>
            <%= f.label :status, "doing", class: 'form-label' %>
            <%= f.check_box(:status, {}, checked_value = 1, unchecked_value = 0 ) %><br>
            <%= fields_for daily_task do |c| %>
              <i class="fa fa-sun-o form-label" aria-hidden="true"></i>
              <%= c.radio_button :condition, 3, id: 'doing', onclick: 'change();', checked: 'checked' %>
              <i class="fa fa-cloud form-label" aria-hidden="true"></i>
              <%= c.radio_button :condition, 2, id: 'doing', onclick: 'change();' %>
              <i class="fa fa-umbrella form-label" aria-hidden="true"></i>
              <%= c.radio_button :condition, 1, id: 'doing', onclick: 'change();' %>
              <%= hidden_field_tag :daily_task_id,daily_task.id %><br>
              <span id="face"> 
                <%= c.label :comment, "face and think", placeholder:'なぜうまくいかなかったのか、どうしたらうまくいくか' %><br>
                <%= c.text_area :comment %>
              </span>
              <%= f.submit %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>


  

app/views/users/done.html.erb
<div class="container">
  <div class="mt-3">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><%= link_to "ToDo", "/users/#{current_user.id}/todo", class: 'nav-link btn-secondary', data: {"turbolinks"=>false}%></li>
      <li class="nav-item"><%= link_to "Doing", "/users/#{current_user.id}/doing", class: 'nav-link btn-secondary', data: {"turbolinks"=>false}%></li>
      <li class="nav-item"><%= link_to "Done", "/users/#{current_user.id}/done", class: 'nav-link active', data: {"turbolinks"=>false}%></li>
    </ul>
  </div>

  <% @tasks.each do |task| %>
    <div class="task">
      <ul>
        <% if task.project.present? %>
          <li><%= task.project.name %>：<%= task.content %></li>
        <% end %>
        <ul>
          <li>締め切り日：<%= task.deadline %></li>
          <li>完了日：<%= task.updated_at.strftime('%Y-%m-%d') %></li>
        </ul>
      </ul>
    </div>
  <% end %>
</div>

app/views/users/joinings.html.erb
<div class='container'>
  <div class='row mt-3'>
    <h2> <%= '参加しているプロジェクト' %> </h2>
  </div>

  <% @projects.each do |p| %>
    <div class='task form-group'>
      <div class="row">
        <div class='col-md-6'>
          <%= p.name %>
        </div>
        <div class="col-md-2">
          <%= link_to 'タスク', project_path(p), class: 'form-control btn btn-secondary', data: {"turbolinks"=>false} %>
        </div>
        <div class="col-md-2">
          <%= link_to 'メンバー', users_project_path(p), class: 'form-control btn btn-secondary', data: {"turbolinks"=>false}%>
        </div>
        <div class="col-md-2">
          <%= link_to '編集', edit_project_path(p), class: 'form-control btn btn-primary', data: {"turbolinks"=>false}%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='container'>
  <h2 class='mt-3'><%=@user.name%>の振り返り</h2>

  <div class="form-group task">
    <p><%= Date.today  %><%= DailyUser.find_by(user_id: @user.id, add_date: Date.today).face if DailyUser.find_by(user_id: current_user.id, add_date: Date.today).present? %></p>
    <% @daily_tasks_0.each do |t| %>
      <div class=" ml-3 content">
        <p>
          <% if t.condition == 3 %>
            <i class="fa fa-sun-o" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 2 %>
            <i class="fa fa-cloud" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 1 %>
            <i class="fa fa-umbrella" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == nil %>
            <i class="fa fa-question" aria-hidden="true"></i>
          <% end %>
          <% if t.task.project.present?%>
            <%= t.task.project.name %>
          <% end %>
          ：<%= t.task.content %>
          <div>
            <%= t.comment%>
          </div>
        </p>
      </div>
    <% end %>
  </div>

  <div class="form-group task">
    <p><%= Date.today-1 if @daily_tasks_1 %><%= DailyUser.find_by(user_id: @user.id, add_date: Date.today-1).face if DailyUser.find_by(user_id: current_user.id, add_date: Date.today-1).present?%></p>

    <% @daily_tasks_1.each do |t| %>
      <div class=" ml-3 content">
        <p>
          <% if t.condition == 3 %>
            <i class="fa fa-sun-o" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 2 %>
            <i class="fa fa-cloud" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 1 %>
            <i class="fa fa-umbrella" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == nil %>
            <i class="fa fa-question" aria-hidden="true"></i>
          <% end %>
          <%= t.task.project.name if t.task.project %>
          ：<%= t.task.content %>
          <div>
            <%= t.comment%>
          </div>
        </p>
      </div>
    <% end %>
  </div>

  <div class="form-group task">
    <p><%= Date.today-2 if @daily_tasks_2 %><%= DailyUser.find_by(user_id: @user.id, add_date: Date.today-2).face if DailyUser.find_by(user_id: current_user.id, add_date: Date.today-2).present? %></p>

    <% @daily_tasks_2.each do |t| %>
      <div class="ml-3 content">
        <p>
          <% if t.condition == 3 %>
            <i class="fa fa-sun-o" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 2 %>
            <i class="fa fa-cloud" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 1 %>
            <i class="fa fa-umbrella" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == nil %>
            <i class="fa fa-question" aria-hidden="true"></i>
          <% end %>
          <%= t.task.project.name if t.task.project %>
          ：<%= t.task.content %>
          <div>
            <%= t.comment%>
          </div>
        </p>
      </div>
    <% end %>
  </div>

  <div class="form-group task">
    <p><%= Date.today-3 if @daily_tasks_3 %><%= DailyUser.find_by(user_id: @user.id, add_date: Date.today-3).face if DailyUser.find_by(user_id: current_user.id, add_date: Date.today-3).present? %></p>

    <% @daily_tasks_3.each do |t| %>
      <div class=" ml-3 content">
        <p>
          <% if t.condition == 3 %>
            <i class="fa fa-sun-o" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 2 %>
            <i class="fa fa-cloud" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 1 %>
            <i class="fa fa-umbrella" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == nil %>
            <i class="fa fa-question" aria-hidden="true"></i>
          <% end %>
          <%= t.task.project.name if t.task.project %>
          ：<%= t.task.content %>
          <div>
            <%= t.comment%>
          </div>
        </p>
      </div>
    <% end %>
  </div>

  <div class="form-group task">
    <p><%= Date.today-4 if @daily_tasks_4 %><%= DailyUser.find_by(user_id: @user.id, add_date: Date.today-4).face if DailyUser.find_by(user_id: current_user.id, add_date: Date.today-4).present? %></p>

    <% @daily_tasks_4.each do |t| %>
      <div class=" ml-3 content">
        <p>
          <% if t.condition == 3 %>
            <i class="fa fa-sun-o" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 2 %>
            <i class="fa fa-cloud" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 1 %>
            <i class="fa fa-umbrella" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == nil %>
            <i class="fa fa-question" aria-hidden="true"></i>
          <% end %>
          <%= t.task.project.name if t.task.project %>
          ：<%= t.task.content %>
          <div>
            <%= t.comment%>
          </div>
        </p>
      </div>
    <% end %>
  </div>

  <div class="form-group task">
    <p><%= Date.today-5 if @daily_tasks_5 %><%= DailyUser.find_by(user_id: @user.id, add_date: Date.today-5).face if DailyUser.find_by(user_id: current_user.id, add_date: Date.today-5).present? %></p>

    <% @daily_tasks_5.each do |t| %>
      <div class=" ml-3 content">
        <p>
          <% if t.condition == 3 %>
            <i class="fa fa-sun-o" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 2 %>
            <i class="fa fa-cloud" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 1 %>
            <i class="fa fa-umbrella" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == nil %>
            <i class="fa fa-question" aria-hidden="true"></i>
          <% end %>
          <%= t.task.project.name if t.task.project %>
          ：<%= t.task.content %>
          <div>
            <%= t.comment%>
          </div>
        </p>
      </div>
    <% end %>
  </div>

  <div class="form-group task">
    <p><%= Date.today-6 if @daily_tasks_6 %><%= DailyUser.find_by(user_id: @user.id, add_date: Date.today-6).face if DailyUser.find_by(user_id: current_user.id, add_date: Date.today-6).present? %></p>

    <% @daily_tasks_6.each do |t| %>
      <div class=" ml-3 content">
        <p>
          <% if t.condition == 3 %>
            <i class="fa fa-sun-o" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 2 %>
            <i class="fa fa-cloud" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == 1 %>
            <i class="fa fa-umbrella" aria-hidden="true"></i>
          <% end %>
          <% if t.condition == nil %>
            <i class="fa fa-question" aria-hidden="true"></i>
          <% end %>
          <%= t.task.project.name if t.task.project %>
          ：<%= t.task.content %>
          <div>
            <%= t.comment%>
          </div>
        </p>
      </div>
    <% end %>
  </div>

app/views/users/todo.html.erb
<div class= 'container'>
  <div class="mt-3">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><%= link_to "ToDo", "/users/#{current_user.id}/todo", class: 'nav-link active', data: {"turbolinks"=>false}%></li>
      <li class="nav-item"><%= link_to "Doing", "/users/#{current_user.id}/doing", class: 'nav-link btn-secondary', data: {"turbolinks"=>false}%></li>
      <li class="nav-item"><%= link_to "Done", "/users/#{current_user.id}/done", class: 'nav-link btn-secondary', data: {"turbolinks"=>false}%></li>
    </ul>
  </div>

    <% @tasks.each do |task| %>
      <div class='task'>
        <ul>
          <% if task.project.present? %>        
            <li><%= task.project.name %>：<%= task.content %></li>
          <% else %>
            <li><%= task.content %></li>
          <% end %>
          <ul>
            <li>〆切：<%= task.deadline %></li>
          <% if task.daily_tasks.present? && task.daily_tasks.last.add_date == Date.today %>
            <a >Doing</a>
          <% else %>
            <%= form_with(model: task.daily_tasks.build, local: true)do |f| %>
              <%= f.hidden_field :task_id, :value => task.id %>
              <%= hidden_field_tag :user_id, task.user_id %>
              <%= f.submit 'Start ▶︎', class: 'btn btn-main' %>
            <% end %>
          <% end %>
          <div style="display:inline-flex">
            <%= link_to 'タスク編集', edit_task_path(task), class: 'btn', data: {"turbolinks"=>false}%>
          </div>
          <div class="fa fa-trash" aria-hidden="true">
            <%= link_to 'タスク削除', task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
          </div>
          </ul>
        </ul>
      </div>

    <% end %>

</div>